### PR TITLE
Easier fixtures

### PR DESCRIPTION
**Pull request by zeke**
This PR does away with the `electron/electron` submodule and replaces it with a small script that downloads just the docs (instead of the entire electron repo) to `test/fixtures`.

This also adds a contributing guide.

cc @MarshallOfSound

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Woohoo, 🔥 that submodule 👍 

My only concern is currently our processes for fixing docs / changing the linter is as follows.

1. Fix docs in Electron and make a PR
2. Implement new fixes / style in the linter and make a PR
3. Merge the linter PR
4. Bump the linter version in the electron doc PR
5. Merge Electron PR

This means that during step 2 and 3 the tests are run against master with new docs that the tests / linter expects in a branch that isn't merged yet.  I think we should have a clever trick to point the tests at a different commit during that period of time where the doc change isn't in master yet. Thoughts?

**Comment by zeke** [comment]
I'm working on a branch that moves each API into its own file: https://github.com/electron/electron/commits/one-file-per-api

My hope is that once we have eradicated `lib/seeds.js`, we won't need to do this dance so often.

**Comment by MarshallOfSound** [comment]
@zeke 👍 Sounds like a plan to me :D

**Comment by zeke** [comment]
1.14.0

🙌

**Pull request merged**
