### PR TITLE
Allow return value types to be inside links

### LINKED ISSUE #54: Return values which are links in the docs are not interpretted correctly
🔗 https://github.com/electron/electron/pull/7379

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #54 

/cc @zeke

### CODE REVIEW

**Comment by zeke** [comment]
RegExp Tip™ courtesy of @kevinsawicki: If we don't need the matched `a` tag content, we can ignore those "capture blocks" or whatever they're called with the `(?:` prefix.

```js
/^Returns (?:<a.+?>)?<code>(.*?)<\/code>(?:<\/a>)?/g
```

That said, I think what you have is fine.

Easy to add a test?

**Comment by MarshallOfSound** [comment]
^^ Hey look, magical tests of magical things

**Comment by zeke** [comment]
👍

**Comment by zeke** [comment]
1.8.0

**Pull request merged**
