### PR TITLE
Update seeds.js

### PR DESCRIPTION
**Pull request by MarshallOfSound**
/cc @zeke

### CODE REVIEW

**Comment by zeke** [comment]
The submodule is out of date. There are no outstanding docs PRs on electron/electron, so latest master should work now, right?

**Comment by MarshallOfSound** [comment]
Yep, master should work now 👍

**Comment by zeke** [comment]
Hmm what did I do wrong there.. What is your technique for managing the electron/electron commit?

**Comment by MarshallOfSound** [comment]
heh, I just go

```bash
cd vendor/electron
git pull
git checkout master
```

😆 Seems to work 👍

**Comment by zeke** [comment]
That's exactly what I did!

**Comment by MarshallOfSound** [comment]
@zeke Maybe needs a rebase as well?

**Comment by zeke** [comment]
1.12.0

**Pull request merged**
