### PR TITLE
Parse array types as singular types and mark them as collections

### LINKED ISSUE #82: Arrays of "either" types are not being parsed correctly
While documenting thew TouchBar API's I find that the output looked like this.

```js
"constructorMethod": {
  "signature": "(items)",
  "parameters": [
    {
      "name": "items",
      "type": [
        "TouchBarButton",
        "TouchBarColorPicker",
        "TouchBarGroup",
        "TouchBarLabel",
        "TouchBarPopOver",
        "TouchBarSlider"
      ],
      "description": "[]",
      "required": true
    }
  ]
},
```

The `description` is the array indicator.  So although the multiple types were recognized correctly the fact it is an array was not 👍 .

I think to make this work correctly we need to bring in a breaking change where if the type is `foo[]` we say that the type is `foo` and add a new property `collection: true / false` if the type is an array or not.

/cc @zeke

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes #82

Note this is a breaking change so if we're doing semver we should probably major

### CODE REVIEW

**Comment by zeke** [comment]
Sorry for the delay getting back to you on this, @MarshallOfSound. Was away in Paris last week.

Major bump is fine, but what exactly does this break?

**Comment by zeke** [comment]
Looks like this breaks a few tests.

**Comment by MarshallOfSound** [comment]
> Major bump is fine, but what exactly does this break?

> Looks like this breaks a few tests.

Pretty much the tests that failed are the breaking changes.  Anyone currently expected `Type[]` to indicate an array will now just see `Type`.  The `collection` property is the new way of determining if it is an array or not.

**Comment by zeke** [comment]
2.0.0 landed!

**Pull request merged**
