### PR TITLE
Rename bounds to rectangle

### PR DESCRIPTION
**Pull request by MarshallOfSound**

### CODE REVIEW

**Comment by zeke** [comment]
Sorry I missed this, @MarshallOfSound. Is CI failing because the Electron submodule is pointing at a non-existent commit?

**Comment by MarshallOfSound** [comment]
@zeke Yeah, my bad 😆 I just changed the submodule to point at a good commit and fixed up the tests 👍

**Comment by zeke** [comment]
Now that https://github.com/electron/electron/pull/7379 has landed, the submodule can point at master again, right?

**Comment by MarshallOfSound** [comment]
@zeke Yep, I'll point it at master now 👍

**Comment by zeke** [comment]
1.8.2

**Pull request merged**
