### PR TITLE
Enums don't need a description + more changes

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Fixes some issues with the TB doc enums not having descriptions 👍 

/cc @zeke

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Woops, looks like this was stacked on top of #88 🌵

**Comment by MarshallOfSound** [comment]
Kind of just merged all my changes into this PR... 😄

**Comment by zeke** [comment]
screen shot 2017-03-24 at 8 35 43 pm

It'd be cool if we had a bot that would summarize CI failures.

Hey @bkeepers could we do that with probot?

**Comment by MarshallOfSound** [comment]
@zeke When this one goes through https://github.com/electron/electron-definitelytyped/pull/16 can go through, then we'll be 5 linting errors away from a green typescript file 👍

**Comment by bkeepers** [comment]
> It'd be cool if we had a bot that would summarize CI failures.
>
> Hey @bkeepers could we do that with probot?

I'm surprised Travis doesn't have a notifier config to post the build failure to GitHub.

But yeah, you could build that with Probot. You would listen for the [status](https://developer.github.com/v3/activity/events/types/#statusevent) webhook, and if it's `failure` then use the Travis API to get the [logs](https://docs.travis-ci.com/api#logs) and summarize them. I'd be happy to pair with anyone that wants to build that.

cc @janl @gr2m since we've been talking about bots to build

**Pull request merged**
